# Generated by Django 5.1.1 on 2024-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(help_text='Enter your car model', max_length=20)),
                ('dateOfIndustry', models.DecimalField(decimal_places=2, help_text='Enter your date of industry', max_digits=5, verbose_name='date of industry')),
                ('Engine', models.CharField(help_text='Enter your Engine power', max_length=20)),
                ('gearBox', models.CharField(help_text='Enter your gearBox type ', max_length=20)),
                ('Wheel', models.CharField(help_text='Enter your wheel type ', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default='323233', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(help_text='enter your name', max_length=20, verbose_name='this must be your first name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.DecimalField(decimal_places=0, help_text='please enter 10 digit phone number ', max_digits=10),
        ),
    ]
