# Generated by Django 5.1.1 on 2024-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_alter_users_country_alter_users_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diameter', models.DecimalField(decimal_places=0, help_text='Enter your date of industry', max_digits=10, verbose_name='Diameter')),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='carModel',
            new_name='CarModel',
        ),
        migrations.AlterField(
            model_name='car',
            name='dateOfIndustry',
            field=models.DecimalField(decimal_places=0, help_text='Enter your date of industry', max_digits=10, verbose_name='date of industry'),
        ),
    ]
