# Generated by Django 5.1.1 on 2024-10-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_diameter_rename_carmodel_car_carmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.CharField(help_text='Enter your car body', max_length=20)),
            ],
        ),
    ]
