# Generated by Django 5.1.1 on 2024-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfCar', models.CharField(help_text='Enter your Type Of Car', max_length=20)),
                ('NumberOfSeats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('LightingColor', models.CharField(help_text='Enter your color Of light', max_length=20)),
                ('Speed', models.CharField(help_text='Enter your car speed', max_length=20)),
            ],
        ),
    ]
