# Generated by Django 5.1.1 on 2024-10-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_typecar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecar',
            old_name='TypeOfCar',
            new_name='Car_type',
        ),
    ]
