# Generated by Django 5.1.1 on 2024-10-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_rename_typeofcar_typecar_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecar',
            name='Car_type',
            field=models.ForeignKey(help_text='Enter your Type Of Car', on_delete=django.db.models.deletion.CASCADE, related_name='Car_type', to='car.car'),
        ),
    ]
