# Generated by Django 5.1.1 on 2024-10-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_typecar_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecar',
            old_name='Car_type',
            new_name='CarType',
        ),
    ]
