# Generated by Django 5.1.1 on 2024-10-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_rename_car_type_typecar_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecar',
            name='CarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarType', to='car.car'),
        ),
    ]
