# Generated by Django 5.1.1 on 2024-10-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_carinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecar',
            options={'ordering': ['CarType']},
        ),
    ]
