# Generated by Django 5.1.1 on 2024-10-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_typecar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['dateOfIndustry']},
        ),
    ]
