# Generated by Django 4.2.16 on 2025-01-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ['Body']},
        ),
        migrations.AlterModelOptions(
            name='diameter',
            options={'ordering': ['Diameter']},
        ),
    ]
