# Generated by Django 4.2.16 on 2025-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_body_options_alter_diameter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dateOfIndustry',
            field=models.DateField(help_text='Enter your date of industry', verbose_name='date of industry'),
        ),
    ]
