# Generated by Django 4.2.16 on 2025-02-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_car_dateofindustry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['CarModel']},
        ),
    ]
