# Generated by Django 4.2.16 on 2025-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
