# Generated by Django 4.2.16 on 2025-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, help_text='Enter your price ', max_length=20, null=True),
        ),
    ]
